### ISSUE TITLE
Hello, low speed quastion

### ISSUE THREAD

**Issue by allexstorm** [optinsoft/gen_eth#3]
I contacted author by email but no reply, writing here, maybe somebody will reply.

I get speed only about 8000 addresses per second, when as I read it should be millions per second with gpu. I have gtx 1650 ti

I have script with cpu and I get about 2000 addresses per core, 12000 per 6 cores per second. I don’t understand why is so small with your cuda implementation.

Please advice.

**Comment by optinsoft** [comment]
That is possibly because of poor performance of python part (generation of random keys blocks). 
Also try playing with blockSize and blockIterations parameters.
